apiVersion: v1
kind: Service
metadata:
  name: url-shortener
  namespace: default
  labels:
    app: url-shortener
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 443
  selector:
    app: url-shortener
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
  labels:
    app: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: rubenwo/url-shortener:latest
          ports:
            - containerPort: 443
          imagePullPolicy: Always
